name: 'Bloxberg certifier'
description: 'Certifies your code or documents'
author: 'Max Planck Digital Library'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  authorName:
    description: 'Enter your group or author(s) research was conducted with'
    required: false
    default: 'fgrgtgtgt'
  bloxbergAddress:
    description: 'Enter your bloxberg address that you would like the certification to be minted to'
    required: false
    default: '0x9858eC18a269EE69ebfD7C38eb297996827DDa98'
  researchTitle:
    description: 'Enter a brief description of what the data entails'
    required: false
    default: 'jrgrg'
  email:
    description: 'If you wish an email address to be associated with the data'
    required: false
    default: 'i3378047@gmail.com'

# Define your outputs here.
outputs:
  certificateVerification:
    description: 'JSON data to verify the certificate on https://certify.bloxberg.org/'

runs:
  using: node20
  main: dist/index.js
